#include "../../events.h"
#include "edgeguard_meta.h"

static EventMatchData FoxEdgeguard_MatchData = {
    .timer = MATCH_TIMER_COUNTUP,
    .matchType = MATCH_MATCHTYPE_TIME,
    .isDisableMusic = true,
    .hideGo = true,
    .hideReady = true,
    .isCreateHUD = true,
    .isDisablePause = true,
    .timerRunOnPause = false,
    .isHidePauseHUD = true,
    .isShowLRAStart = true,
    .isCheckForLRAStart = true,
    .isShowZRetry = true,
    .isCheckForZRetry = true,
    .isShowAnalogStick = true,
    .isShowScore = false,

    .isRunStockLogic = false,
    .isDisableHit = false,
    .useKOCounter = false,
    .playerKind = -1,
    .cpuKind = CKIND_FOX,
    .stage = -1,
    .timerSeconds = 0,
    .timerSubSeconds = 0,
};
EventDesc FoxEdgeguard = {
    .eventName = "Fox Edgeguard Training\n",
    .eventDescription = "Finish off the enemy Fox\nafter you hit him offstage!",
    .eventFile = "edgeguard",
    .jumpTableIndex = -1,
    .CSSType = SLCHRKIND_EVENT,
    .CSSList = NULL,
    .isSelectStage = true,
    .use_savestates = false,
    .disable_hazards = true,
    .force_sopo = false,
    .scoreType = SCORETYPE_KO,
    .callbackPriority = 3,
    .matchData = &FoxEdgeguard_MatchData,
    .defaultOSD = 0xFFFFFFFF,
};

static EventMatchData FalcoEdgeguard_MatchData = {
    .timer = MATCH_TIMER_COUNTUP,
    .matchType = MATCH_MATCHTYPE_TIME,
    .isDisableMusic = true,
    .hideGo = true,
    .hideReady = true,
    .isCreateHUD = true,
    .isDisablePause = true,
    .timerRunOnPause = false,
    .isHidePauseHUD = true,
    .isShowLRAStart = true,
    .isCheckForLRAStart = true,
    .isShowZRetry = true,
    .isCheckForZRetry = true,
    .isShowAnalogStick = true,
    .isShowScore = false,

    .isRunStockLogic = false,
    .isDisableHit = false,
    .useKOCounter = false,
    .playerKind = -1,
    .cpuKind = CKIND_FALCO,
    .stage = -1,
    .timerSeconds = 0,
    .timerSubSeconds = 0,
};
EventDesc FalcoEdgeguard = {
    .eventName = "Falco Edgeguard Training\n",
    .eventDescription = "Finish off the enemy Falco\nafter you hit him offstage!",
    .eventFile = "edgeguard",
    .jumpTableIndex = -1,
    .CSSType = SLCHRKIND_EVENT,
    .CSSList = NULL,
    .isSelectStage = true,
    .use_savestates = false,
    .disable_hazards = true,
    .force_sopo = false,
    .scoreType = SCORETYPE_KO,
    .callbackPriority = 3,
    .matchData = &FalcoEdgeguard_MatchData,
    .defaultOSD = 0xFFFFFFFF,
};